version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - 3306:3306
    networks:
      - express_net
    volumes:
      - mysql_vol:/var/lib/mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
  app:
    image: express-image
    container_name: express-app
    build: .
    ports:
      - 3000:3000
    networks:
      - express_net
    depends_on:
      - db
    restart: always
    working_dir: /app
    command: 'npm run start'
networks:
  express_net:
volumes:
  mysql_vol:
